# DESAFIO 009 - Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.

n = int(input('Digite um número para obter sua tabuada: '))
print('-'*15)
print('{} x 1 = {}.'.format(n,n))
print('{} x 2 = {}.'.format(n,2*n))
print('{} x 3 = {}.'.format(n, 3*n))
print('{} x 4 = {}.'.format(n,4*n))
print('{} x 5 = {}.'.format(n,5*n))
print('{} x 6 = {}.'.format(n,6*n))
print('{} x 7 = {}.'.format(n,7*n))
print('{} x 8 = {}.'.format(n,8*n))
print('{} x 9 = {}.'.format(n,9*n))
print('{} x 10 = {}.'.format(n,10*n))
print('-'*15)